### ISSUE TITLE
Installation under Ubuntu 24 fails

### ISSUE THREAD

**Issue by TimHal** [GrHound/UnipenTools2023#1]
The installation script does not complete when run on Ubuntu 24.04.1 LTS using a Dell XPS 15. 

**Steps to reproduce**
Using a fresh Ubuntu install, and having the project checked out:
 1) run `./install`  from the project root directory 

**Expected Behaviour**

The application should be installed as described in the `README` file.

**Actual Behaviour**

The installation fails and thus has a non-zero return code.

**Error Message**
```
gcc -o ../bin/unipen2eps unipen2eps.o \
	../Uplib/lib/libuplib6.a  -L/usr/X11R6/lib -lXmu -lm -static -static-libgcc
/usr/bin/ld: cannot find -lXmu: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:67: ../bin/unipen2eps] Error 1

```

**Comment by TimHal** [comment]
This problem is caused by missing the appropriate x11 dependencies for `upview`. To install them, run 
 `sudo apt install libxmu-dev libx11-dev` and then execute the install script again.
 
 I just wanted to report this, in case someone else runs into the same error.

**Comment by GrHound** [comment]
Thanks! Unfortunately X11 is fading to the background.

Lambert

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
